// src/features/admin/components/AdminInquiriesSection.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useAdminApi } from "../../../composables/useAdminApi";

type Inquiry = {
  id: string;
  inquiry_type: string;
  message: string;
  needs_admin: boolean;
  user_email: string | null;
  user_name: string | null;
  created_at: string;
};

const { adminFetch } = useAdminApi();
const inquiries = ref<Inquiry[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);

onMounted(async () => {
  try {
    const res = await adminFetch("/api/admin/inquiries");
    if (!res.ok) {
      const body = (await res.json().catch(() => ({}))) as { error?: string };
      error.value = body.error ?? `Failed to load (${res.status})`;
      return;
    }
    const data = (await res.json()) as { inquiries?: Inquiry[] };
    inquiries.value = data.inquiries ?? [];
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to load inquiries";
  } finally {
    loading.value = false;
  }
});
</script>

<template>
  <section class="admin-section">
    <h2>Contact inquiries</h2>
    <p v-if="loading" class="admin-note">Loading…</p>
    <p v-else-if="error" class="admin-note">{{ error }}</p>
    <p v-else-if="inquiries.length === 0" class="admin-note">No inquiries yet.</p>
    <ul v-else class="admin-inquiries">
      <li
        v-for="item in inquiries"
        :key="item.id"
        class="admin-inquiry"
        :class="{ 'admin-inquiry-urgent': item.needs_admin }"
      >
        <div class="admin-inquiry-meta">
          <span class="admin-inquiry-type">{{ item.inquiry_type }}</span>
          <span v-if="item.needs_admin" class="admin-inquiry-badge">Needs review</span>
        </div>
        <p v-if="item.user_name || item.user_email" class="admin-inquiry-user">
          {{ item.user_name ?? "Guest" }}
          <span v-if="item.user_email"> · {{ item.user_email }}</span>
        </p>
        <p class="admin-inquiry-message">{{ item.message }}</p>
        <time class="admin-inquiry-time">{{ new Date(item.created_at).toLocaleString() }}</time>
      </li>
    </ul>
  </section>
</template>

<style scoped lang="scss">
.admin-section {
  display: flex;
  flex-direction: column;
  gap: var(--space-md);

  h2 {
    font-size: var(--font-size-lg);
    font-weight: 800;
    color: var(--color-text-400);
  }
}

.admin-note {
  font-size: var(--font-size-sm);
  color: var(--color-text-300);
}

.admin-inquiries {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: var(--space-md);
}

.admin-inquiry {
  padding: var(--space-md);
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-md);
  display: flex;
  flex-direction: column;
  gap: var(--space-xs);

  &-urgent {
    border-color: var(--color-accent-400);
    background: rgba(232, 93, 4, 0.06);
  }

  &-meta {
    display: flex;
    align-items: center;
    gap: var(--space-sm);
  }

  &-badge {
    font-size: var(--font-size-xxs);
    font-weight: 700;
    text-transform: uppercase;
    color: var(--color-accent-400);
    padding: 2px 8px;
    border-radius: 999px;
    background: rgba(232, 93, 4, 0.12);
  }

  &-user {
    font-size: var(--font-size-xs);
    color: var(--color-text-300);
  }

  &-type {
    font-size: var(--font-size-xs);
    font-weight: 700;
    text-transform: uppercase;
    color: var(--color-accent-400);
  }

  &-message {
    font-size: var(--font-size-sm);
    color: var(--color-text-400);
  }

  &-time {
    font-size: var(--font-size-xxs);
    color: var(--color-text-300);
  }
}
</style>

// src/components/admin/AdminInquiriesSection.tsx
import { useEffect, useState } from "react";
import { useAuth } from "@clerk/clerk-react";

type Inquiry = {
  id: string;
  inquiry_type: string;
  message: string;
  needs_admin: boolean;
  user_email: string | null;
  user_name: string | null;
  intake: Record<string, unknown> | null;
  created_at: string;
};

export function AdminInquiriesSection() {
  const { getToken } = useAuth();
  const [inquiries, setInquiries] = useState<Inquiry[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    setError(null);
    const token = await getToken();
    if (!token) return;
    const res = await fetch("/api/admin/inquiries", {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) {
      setError("Failed to load inquiries");
      setLoading(false);
      return;
    }
    const data = (await res.json()) as { inquiries?: Inquiry[] };
    setInquiries(data.inquiries ?? []);
    setLoading(false);
  };

  useEffect(() => {
    void load();
  }, [getToken]);

  if (loading) return <p className="text-sm text-[var(--text-muted)]">Loading inquiries…</p>;
  if (error) return <p className="text-sm text-red-500">{error}</p>;

  if (inquiries.length === 0) {
    return <p className="text-sm text-[var(--text-muted)]">No inquiries yet.</p>;
  }

  return (
    <ul className="space-y-3">
      {inquiries.map((item) => (
        <li
          key={item.id}
          className={`rounded-xl border p-3 text-sm ${
            item.needs_admin ? "border-[var(--color-accent)] bg-orange-500/5" : "border-[var(--border)]"
          }`}
        >
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-bold uppercase text-[var(--color-accent)]">{item.inquiry_type}</span>
            {item.needs_admin && (
              <span className="rounded-full bg-orange-500/15 px-2 py-0.5 text-[10px] font-bold uppercase">
                Urgent
              </span>
            )}
            <time className="ml-auto text-[10px] text-[var(--text-muted)]">
              {new Date(item.created_at).toLocaleString()}
            </time>
          </div>
          {(item.user_name || item.user_email) && (
            <p className="mt-1 text-xs text-[var(--text-muted)]">
              {item.user_name}
              {item.user_email ? ` · ${item.user_email}` : ""}
            </p>
          )}
          {item.intake && Object.keys(item.intake).length > 0 && (
            <pre className="mt-2 overflow-x-auto rounded-lg bg-[var(--bg)] p-2 text-[10px] leading-relaxed text-[var(--text-muted)]">
              {JSON.stringify(item.intake, null, 2)}
            </pre>
          )}
          <p className="mt-2 whitespace-pre-wrap">{item.message}</p>
        </li>
      ))}
    </ul>
  );
}
