// src/features/chat/ChatPage.vue
<script setup lang="ts">
import { defineAsyncComponent } from "vue";
import { t } from "../../i18n/utils/translate";
import { useRouter } from "../../composables/useRouter";
import { isClerkConfigured } from "../../lib/clerk";

const ContactChatPanel = isClerkConfigured
  ? defineAsyncComponent(() => import("../../components/ContactChatPanel.vue"))
  : null;

const router = useRouter();

const goHome = () => {
  router.push("/");
};
</script>

<template>
  <div class="chat-page">
    <main class="chat-page-main">
      <div class="chat-page-intro">
        <h1 class="chat-page-title">{{ t("chat-title") }}</h1>
        <p class="chat-page-subtitle">{{ t("chat-subtitle") }}</p>
      </div>

      <div v-if="!isClerkConfigured" class="chat-page-gate">
        <p>{{ t("chat-clerk-missing") }}</p>
        <button type="button" class="chat-page-home-link" @click="goHome">{{ t("back-to-home") }}</button>
      </div>
      <ContactChatPanel v-else fixed class="chat-page-panel" />
    </main>
  </div>
</template>

<style scoped lang="scss">
.chat-page {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--color-background-400);
  overflow: hidden;

  &-intro {
    flex-shrink: 0;
    padding-bottom: var(--space-sm);
  }

  &-title {
    font-size: var(--font-size-md);
    font-weight: 800;
    color: var(--color-text-400);

    @include mixins.mq("md") {
      font-size: var(--font-size-lg);
    }
  }

  &-subtitle {
    font-size: var(--font-size-sm);
    color: var(--color-text-300);
    margin-top: var(--space-xxs);
  }

  &-main {
    flex: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
    width: 100%;
    max-width: 840px;
    margin: 0 auto;
    padding: var(--space-sm) var(--space-outer);
    padding-bottom: calc(72px + env(safe-area-inset-bottom, 0px));
    overflow: hidden;

    @include mixins.mq("lg") {
      max-width: none;
      padding-inline: var(--space-lg);
    }
  }

  &-panel {
    flex: 1;
    min-height: 0;
    display: flex;
    flex-direction: column;
  }

  &-gate {
    display: flex;
    flex-direction: column;
    gap: var(--space-md);
    color: var(--color-text-300);
    padding: var(--space-xl) 0;
  }

  &-home-link {
    align-self: flex-start;
    border: none;
    background: none;
    color: var(--color-accent-400);
    font: inherit;
    font-weight: 600;
    cursor: pointer;
    padding: 0;
  }
}
</style>

// src/pages/ChatPage.tsx
import { Link } from "react-router-dom";
import { ContactChatPanel } from "@/components/chat/ContactChatPanel";
import { isClerkConfigured } from "@/lib/clerk";
import { t } from "@/i18n/en";

export function ChatPage() {
  return (
    <main className="mx-auto flex h-[calc(100dvh-4.5rem)] max-w-3xl flex-col px-4 pb-6 pt-20 sm:px-6">
      <div className="mb-4 shrink-0">
        <Link to="/" className="text-xs font-semibold text-[var(--text-muted)] hover:text-[var(--color-accent)]">
          ← {t("back-to-home")}
        </Link>
        <h1 className="mt-3 text-xl font-black md:text-2xl">{t("chat-title")}</h1>
        <p className="mt-1 text-sm text-[var(--text-muted)]">{t("chat-subtitle")}</p>
      </div>

      {!isClerkConfigured ? (
        <div className="rounded-2xl border border-[var(--border)] bg-[var(--bg-elevated)] p-6 text-sm text-[var(--text-muted)]">
          <p>{t("chat-clerk-missing")}</p>
          <Link to="/" className="mt-4 inline-block font-semibold text-[var(--color-accent)]">
            {t("back-to-home")}
          </Link>
        </div>
      ) : (
        <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--bg-elevated)] shadow-lg">
          <ContactChatPanel fixed />
        </div>
      )}
    </main>
  );
}
