// src/components/layout/MobileNav.tsx
import { useEffect, useState, type ReactNode } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { t } from "@/i18n/en";
import { getLenis } from "@/hooks/useScroll";

type NavSection = "hero" | "about" | "projects" | "chat";

function NavIcon({ children }: { children: ReactNode }) {
  return <span className="h-5 w-5 [&_svg]:h-full [&_svg]:w-full">{children}</span>;
}

function IconHome() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M4 10.5L12 4l8 6.5V20a1 1 0 0 1-1 1h-5v-6H10v6H5a1 1 0 0 1-1-1v-9.5z"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function IconAbout() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden>
      <circle cx="12" cy="8" r="3.5" stroke="currentColor" strokeWidth="1.8" />
      <path
        d="M6 20c0-3.3 2.7-6 6-6s6 2.7 6 6"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
    </svg>
  );
}

function IconProjects() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M4 7h6l2 2h8v10H4V7z"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinejoin="round"
      />
      <path d="M4 7V5a1 1 0 0 1 1-1h5l2 2h7a1 1 0 0 1 1 1v2" stroke="currentColor" strokeWidth="1.8" />
    </svg>
  );
}

function IconChat() {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M12 3C7.03 3 3 6.58 3 11c0 2.03.9 3.88 2.4 5.28L4 21l5.05-1.35A9.8 9.8 0 0 0 12 19c4.97 0 9-3.58 9-8s-4.03-8-9-8z"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinejoin="round"
      />
    </svg>
  );
}

const scrollItems: { id: Exclude<NavSection, "chat" | "hero">; icon: typeof IconAbout; labelKey: "about" | "projects" }[] = [
  { id: "about", icon: IconAbout, labelKey: "about" },
  { id: "projects", icon: IconProjects, labelKey: "projects" },
];

export function MobileNav() {
  const location = useLocation();
  const navigate = useNavigate();
  const [activeSection, setActiveSection] = useState<NavSection | null>("hero");

  const isChatRoute = location.pathname.startsWith("/chat");
  const isProjectRoute = location.pathname.startsWith("/project/");
  const isHome = location.pathname === "/";
  const hidden = isProjectRoute;

  const scrollToSection = (section: NavSection) => {
    setActiveSection(section);
    const lenis = getLenis();
    const target = section === "hero" ? 0 : `#${section}`;

    if (lenis) {
      lenis.scrollTo(target, { immediate: section === "hero" });
      requestAnimationFrame(() => ScrollTrigger.refresh());
      return;
    }

    if (section === "hero") {
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }

    document.getElementById(section)?.scrollIntoView({ behavior: "smooth" });
  };

  const scrollTo = (section: NavSection) => {
    if (section === "chat") {
      navigate("/chat");
      setActiveSection("chat");
      return;
    }

    if (!isHome) {
      navigate("/");
      window.setTimeout(() => scrollToSection(section), 50);
      return;
    }

    scrollToSection(section);
  };

  useEffect(() => {
    if (isChatRoute) {
      setActiveSection("chat");
      return;
    }

    if (!isHome) {
      setActiveSection(null);
      return;
    }

    const sections: { id: Exclude<NavSection, "chat">; trigger: string }[] = [
      { id: "hero", trigger: "#hero" },
      { id: "about", trigger: "#about" },
      { id: "projects", trigger: "#projects" },
    ];

    const observers = sections.map(({ id, trigger }) => {
      const el = document.querySelector(trigger);
      if (!el) return null;

      const observer = new IntersectionObserver(
        ([entry]) => {
          if (entry?.isIntersecting) setActiveSection(id);
        },
        { rootMargin: "-45% 0px -45% 0px", threshold: 0 },
      );
      observer.observe(el);
      return observer;
    });

    return () => observers.forEach((o) => o?.disconnect());
  }, [isChatRoute, isHome, location.pathname]);

  if (hidden) return null;

  return (
    <div
      className="fixed bottom-[calc(12px+env(safe-area-inset-bottom,0px))] left-1/2 z-[90] flex w-[calc(100%-24px)] max-w-[420px] -translate-x-1/2 items-center justify-center md:hidden"
      aria-label="Mobile navigation"
    >
      <nav className="flex w-full items-center justify-around gap-0.5 rounded-full border border-white/10 bg-[rgba(15,20,25,0.88)] px-2 py-1.5 shadow-[0_8px_40px_rgba(0,0,0,0.35)] backdrop-blur-xl [data-theme=light]:border-[rgba(26,29,33,0.08)] [data-theme=light]:bg-[rgba(255,255,255,0.92)] [data-theme=light]:shadow-[0_8px_40px_rgba(0,0,0,0.12)]">
        <button
          type="button"
          className={`flex min-w-0 flex-1 flex-col items-center justify-center gap-0.5 rounded-full border-0 bg-transparent px-1 py-2 font-[inherit] text-[10px] font-semibold tracking-wide transition ${
            activeSection === "hero"
              ? "bg-white/12 text-white [data-theme=light]:text-[var(--text)]"
              : "text-white/55 [data-theme=light]:text-[rgba(26,29,33,0.45)]"
          }`}
          onClick={() => scrollTo("hero")}
          aria-label={t("home")}
          aria-current={activeSection === "hero" ? "page" : undefined}
        >
          <NavIcon>
            <IconHome />
          </NavIcon>
          <span>{t("home")}</span>
        </button>

        {scrollItems.map(({ id, icon: Icon, labelKey }) => (
          <button
            key={id}
            type="button"
            className={`flex min-w-0 flex-1 flex-col items-center justify-center gap-0.5 rounded-full border-0 bg-transparent px-1 py-2 font-[inherit] text-[10px] font-semibold tracking-wide transition ${
              activeSection === id
                ? "bg-white/12 text-white [data-theme=light]:text-[var(--text)]"
                : "text-white/55 [data-theme=light]:text-[rgba(26,29,33,0.45)]"
            }`}
            onClick={() => scrollTo(id)}
            aria-label={t(labelKey)}
            aria-current={activeSection === id ? "page" : undefined}
          >
            <NavIcon>
              <Icon />
            </NavIcon>
            <span>{t(labelKey)}</span>
          </button>
        ))}

        <button
          type="button"
          className={`flex min-w-0 flex-1 flex-col items-center justify-center gap-0.5 rounded-full border-0 bg-transparent px-1 py-2 font-[inherit] text-[10px] font-semibold tracking-wide transition ${
            activeSection === "chat"
              ? "bg-white/12 text-white [data-theme=light]:text-[var(--text)]"
              : "text-white/55 [data-theme=light]:text-[rgba(26,29,33,0.45)]"
          }`}
          onClick={() => scrollTo("chat")}
          aria-label={t("chat")}
          aria-current={activeSection === "chat" ? "page" : undefined}
        >
          <NavIcon>
            <IconChat />
          </NavIcon>
          <span>{t("chat")}</span>
        </button>
      </nav>
    </div>
  );
}

// src/components/MobileNav.vue
<script setup lang="ts">
import { ref, onMounted, watch } from "vue";
import { t } from "../i18n/utils/translate";
import { lenis } from "../composables/useScroll";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { path, projectId } from "../composables/useRouteObserver";
import { useRouter } from "../composables/useRouter";
import ProfileNavButton from "./ProfileNavButton.vue";
import NavHome from "./icons/NavHome.vue";
import NavAbout from "./icons/NavAbout.vue";
import NavProjects from "./icons/NavProjects.vue";
import NavChat from "./icons/NavChat.vue";

type NavSection = "hero" | "about" | "projects" | "chat";

const router = useRouter();
const activeSection = ref<NavSection | null>(null);

const scrollItems: { id: Exclude<NavSection, "chat">; icon: typeof NavHome; labelKey: "about" | "projects" }[] = [
  { id: "about", icon: NavAbout, labelKey: "about" },
  { id: "projects", icon: NavProjects, labelKey: "projects" },
];

const isChatRoute = () => path.value === "/chat" || path.value.startsWith("/chat/");

const scrollTo = (section: NavSection) => {
  if (section === "chat") {
    router.push("/chat");
    activeSection.value = "chat";
    return;
  }
  if (!lenis.value) return;
  activeSection.value = section;
  lenis.value.scrollTo(section === "hero" ? 0 : `#${section}`);
};

onMounted(() => {
  const sections: Exclude<NavSection, "chat">[] = ["hero", "about", "projects"];

  sections.forEach((section) => {
    const trigger = section === "hero" ? "#hero" : `#${section}`;
    ScrollTrigger.create({
      trigger,
      start: section === "hero" ? "top 40%" : section === "about" ? "top 30%" : "top center",
      end: "bottom center",
      onEnter: () => {
        if (!isChatRoute()) activeSection.value = section;
      },
      onEnterBack: () => {
        if (!isChatRoute()) activeSection.value = section;
      },
    });
  });

  if (isChatRoute()) activeSection.value = "chat";
});

watch(path, () => {
  if (isChatRoute()) {
    activeSection.value = "chat";
  } else if (activeSection.value === "chat") {
    activeSection.value = null;
  }
});
</script>

<template>
  <div
    class="mobile-nav-wrap"
    :class="{ 'mobile-nav-wrap-hidden': projectId !== null }"
    aria-label="Mobile navigation"
  >
    <nav class="mobile-nav-pill">
      <button
        type="button"
        class="mobile-nav-item"
        :class="{ 'mobile-nav-item-active': activeSection === 'hero' }"
        @click="scrollTo('hero')"
        data-sound="click"
        :aria-label="t('back-to-home')"
      >
        <NavHome class="mobile-nav-icon" />
        <span class="mobile-nav-label">{{ t("home") }}</span>
      </button>

      <button
        v-for="item in scrollItems"
        :key="item.id"
        type="button"
        class="mobile-nav-item"
        :class="{ 'mobile-nav-item-active': activeSection === item.id }"
        @click="scrollTo(item.id)"
        data-sound="click"
        :aria-label="t(item.labelKey)"
      >
        <component :is="item.icon" class="mobile-nav-icon" />
        <span class="mobile-nav-label">{{ t(item.labelKey) }}</span>
      </button>

      <button
        type="button"
        class="mobile-nav-item"
        :class="{ 'mobile-nav-item-active': activeSection === 'chat' }"
        @click="scrollTo('chat')"
        data-sound="click"
        :aria-label="t('chat')"
      >
        <NavChat class="mobile-nav-icon" />
        <span class="mobile-nav-label">{{ t("chat") }}</span>
      </button>
    </nav>

    <ProfileNavButton />
  </div>
</template>

<style scoped lang="scss">
.mobile-nav-wrap {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  position: fixed;
  bottom: calc(12px + env(safe-area-inset-bottom, 0px));
  left: 50%;
  transform: translateX(-50%);
  z-index: var(--z-index-mobile-nav);
  width: calc(100% - 24px);
  max-width: 420px;
  transition: transform 0.35s var(--ease-smooth), opacity 0.25s ease;

  @include mixins.mq("lg") {
    display: none;
  }

  &-hidden {
    transform: translateX(-50%) translateY(calc(100% + 24px));
    opacity: 0;
    pointer-events: none;
  }
}

.mobile-nav-pill {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: space-around;
  gap: 2px;
  padding: 6px 8px;
  border-radius: 999px;
  background: rgba(15, 20, 25, 0.72);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 0 8px 40px rgba(0, 0, 0, 0.28);
}

[data-theme="light"] .mobile-nav-pill {
  background: rgba(255, 255, 255, 0.88);
  border-color: rgba(26, 29, 33, 0.08);
  box-shadow: 0 8px 40px rgba(0, 0, 0, 0.1);
}

.mobile-nav-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  min-width: 0;
  padding: 8px 4px;
  border: none;
  background: transparent;
  color: rgba(255, 255, 255, 0.55);
  font-family: inherit;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.02em;
  border-radius: 999px;
  cursor: pointer;
  transition:
    color 0.15s ease,
    background-color 0.15s ease;

  &-active {
    color: #fff;
    background: rgba(255, 255, 255, 0.12);
  }
}

[data-theme="light"] .mobile-nav-item {
  color: rgba(26, 29, 33, 0.45);

  &-active {
    color: var(--color-text-400);
    background: rgba(26, 29, 33, 0.08);
  }
}

.mobile-nav-icon {
  width: 22px;
  height: 22px;
  flex-shrink: 0;
}

.mobile-nav-label {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
}
</style>
